### PR TITLE
docs: add zeabur deploy button

### PR DESCRIPTION
**Pull request by yuaanlin**
This Pull Request add a [Zeabur](https://zeabur.com) deploy button on `README.md` to let users who want to self-host their Statusnook can deploy it with one click.

[Deploy on Zeabur](https://zeabur.com/templates/STATOK)

## Demo Video

[](https://www.youtube.com/watch?v=UzM32IUKSFQ)

### CODE REVIEW

**Comment by goksan** [comment]
Hi @yuaanlin, thank you for sharing the Zeabur deploy button, the platform looks interesting.

I'd like to learn more about the following:

- Which deployment path does this template use?
- Will the template be regularly updated? If so, how?
- Could you provide a direct contact method for me to reach out regarding future inquiries about this template?

Additionally, could you please add links to https://statusnook.com and our GitHub page at https://github.com/goksan for users seeking more information?

Thank you!

**Comment by yuaanlin** [comment]
> Which deployment path does this template use?

This template contains a **Prebuilt** Statusnook service. You can see the detail of this prebuilt service at https://github.com/zeabur/zeabur/blob/main/prebuilts/statusnook.toml

```yaml
#:schema ./schema.json

id = "statusnook"
name = "Statusnook"
description = "Effortlessly deploy a status page and start monitoring endpoints in minutes."
icon = "https://icons.zeabur.com/statusnook.png"
tags = ["Monitoring"]

[source]
image = "goksan/statusnook:latest"

[[ports]]
id = "web"
port = 8000
type = "HTTP"

[[volumes]]
id = "data"
dir = "/app/statusnook-data"
```

> Will the template be regularly updated? If so, how?

Since the prebuilt image use the `latest` tag, the template will keep up to date when you release a new version of docker image.

If there is some configuration updates needed, you can contact us or submit a PR to [here](https://github.com/zeabur/zeabur/blob/main/prebuilts/statusnook.toml) directly.

> Could you provide a direct contact method for me to reach out regarding future inquiries about this template?

Sure, you can contact me via email `yuanlin@zeabur.com` or join the Zeabur official Discord channel at https://zeabur.com/dc .
 
> Additionally, could you please add links to https://statusnook.com and our GitHub page at https://github.com/goksan/statusnook for users seeking more information?

No problem, these links have been added to the template description.

**Comment by goksan** [comment]
Thank you for helping me out with that info!

> No problem, these links have been added to the template description.

I can't find anything at https://zeabur.com/templates/STATOK

**Comment by goksan** [comment]
> > I can't find anything at https://zeabur.com/templates/STATOK
> 
> I think it's a cache issue, can you try refresh the page without cache?
> 
> In MacOS, it's `cmd`+`shift`+`R`.
> image

Strange I tried clearing the cache yesterday and it didn't help, I was able to immediately see it today 👍

**Pull request merged**
